/** Hall3D view – BP-002 structural configuration extension. */
import { commitHallCreate } from "../../core/hall/hall-create.v1.js";
import { HALL_INDUSTRY_GABLE_V1 } from "../../core/hall/hall-config.v1.js";
import { HALL_EDIT_WALL_IDS } from "../../core/hall/hall-edit.v1.js";
import { commitHallStructuralEdit } from "../../core/hall/hall-edit.v2.js";
import { STRUCTURAL_PROFILES_V1 } from "../../core/library/structural-profiles.v1.js";
import { initScene } from "./core/scene.js";
import { ModelFactory } from "./core/model-factory.js";

const ROOF_LABELS={flat:"Flachdach",gable:"Satteldach",mono:"Pultdach"};
const WALL_LABELS={"wall:x0":"Stirnwand X0","wall:xMax":"Stirnwand X max","wall:z0":"Längswand Z0","wall:zMax":"Längswand Z max"};
function style(e,r){Object.assign(e.style,r);return e;} function makeLabel(t){const e=document.createElement("label");e.textContent=t;return style(e,{fontSize:"12px",opacity:".82"});}
function makeNumberInput(v,{min=null,step="0.1"}={}){const i=document.createElement("input");i.type="number";i.value=v==null?"":String(v);i.step=String(step);if(min!=null)i.min=String(min);return style(i,{width:"100%",boxSizing:"border-box",padding:"7px 8px",borderRadius:"7px",border:"1px solid rgba(255,255,255,.18)",background:"rgba(255,255,255,.08)",color:"inherit"});}
function makeSelect(options,value){const s=document.createElement("select");for(const o of options){const e=document.createElement("option");e.value=o.value;e.textContent=o.label;s.appendChild(e);}s.value=value;return style(s,{width:"100%",boxSizing:"border-box",padding:"7px 8px",borderRadius:"7px",border:"1px solid rgba(255,255,255,.18)",background:"rgba(24,28,34,.96)",color:"inherit"});}
function addField(g,l,c){g.appendChild(makeLabel(l));g.appendChild(c);} const profileOptions=()=>STRUCTURAL_PROFILES_V1.map(p=>({value:p.id,label:p.designation}));

export function createHall3DView({bus,store,rootEl}){
 let sceneCtx=null,currentGroup=null,elementMeshes=new Map(),editorHost=null;
 const currentProject=()=>store.get("app")?.project||null;
 function clearStatusAttributes(){try{delete rootEl.dataset.hall3dStatus;delete rootEl.dataset.hallAuthority;}catch(_){}}
 function showStatus(message,status){rootEl.innerHTML="";const note=document.createElement("div");note.textContent=message;style(note,{padding:"16px",fontFamily:"system-ui",fontSize:"13px",opacity:".8"});rootEl.appendChild(note);rootEl.dataset.hall3dStatus=status;rootEl.dataset.hallAuthority="app.project.hall";}
 function renderCreateForm(){rootEl.innerHTML="";rootEl.dataset.hall3dStatus="no-hall";rootEl.dataset.hallAuthority="app.project.hall";const d=HALL_INDUSTRY_GABLE_V1.defaults,host=document.createElement("div");host.dataset.bpHallCreate="project-ui-04a";style(host,{width:"min(430px, calc(100% - 24px))",boxSizing:"border-box",margin:"12px",padding:"14px",borderRadius:"10px",border:"1px solid rgba(127,127,127,.35)",fontFamily:"system-ui"});const title=document.createElement("div");title.textContent="Halle anlegen";style(title,{fontWeight:"700",fontSize:"15px",marginBottom:"10px"});host.appendChild(title);const form=document.createElement("form"),grid=document.createElement("div");form.dataset.bpHallCreateForm="true";style(grid,{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(110px,130px)",gap:"8px 10px",alignItems:"center"});const length=makeNumberInput(d.dimensions.length,{min:1}),width=makeNumberInput(d.dimensions.width,{min:1}),eave=makeNumberInput(d.dimensions.eaveHeight,{min:2}),roof=makeSelect(Object.entries(ROOF_LABELS).map(([value,label])=>({value,label})),d.roof.type),peak=makeNumberInput(d.roof.peakHeight,{min:0}),spacing=makeNumberInput(d.grid.longitudinal.spacing,{min:.5});addField(grid,"Länge [m]",length);addField(grid,"Breite [m]",width);addField(grid,"Traufhöhe [m]",eave);addField(grid,"Dachform",roof);addField(grid,"First / Hochpunkt [m]",peak);addField(grid,"Längsraster [m]",spacing);form.appendChild(grid);const status=document.createElement("div");style(status,{minHeight:"16px",marginTop:"10px",fontSize:"11px"});form.appendChild(status);const submit=document.createElement("button");submit.type="submit";submit.textContent="Halle anlegen";style(submit,{width:"100%",padding:"9px",border:0,borderRadius:"8px",fontWeight:"700"});form.appendChild(submit);form.addEventListener("submit",e=>{e.preventDefault();const type=roof.value,r=commitHallCreate({store,bus,input:{dimensions:{length:Number(length.value),width:Number(width.value),eaveHeight:Number(eave.value)},roof:{type,peakHeight:type==="flat"?null:Number(peak.value)},grid:{longitudinal:{mode:"spacing",spacing:Number(spacing.value)}}}});status.textContent=r.committed?(r.warnings||[]).join(" · "):(r.errors||[]).join(" · ");});host.appendChild(form);rootEl.appendChild(host);}
 function frameHall(built){if(!sceneCtx?.cam||!built?.hall?.dimensions)return;const h=built.hall,{length,width,eaveHeight}=h.dimensions,top=h.roof.type==="flat"?eaveHeight:h.roof.peakHeight,span=Math.max(length,width,top,10),p=h.transform?.position||{},c={x:(+p.x||0)+length/2,y:(+p.y||0)+top*.45,z:(+p.z||0)+width/2};sceneCtx.cam.position.set(c.x+span*.65,c.y+span*.45,c.z+span*.65);sceneCtx.cam.lookAt(c.x,c.y,c.z);}
 function renderEditor(){const hall=currentProject()?.hall;if(!sceneCtx?.container||!hall)return;if(editorHost)editorHost.remove();const host=document.createElement("div");host.dataset.bpHallEdit="rapid-v2";style(host,{position:"absolute",top:"12px",right:"12px",width:"330px",maxWidth:"calc(100% - 24px)",maxHeight:"calc(100% - 24px)",overflow:"auto",boxSizing:"border-box",padding:"12px",borderRadius:"10px",background:"rgba(20,24,30,.90)",color:"#f3f5f7",fontFamily:"system-ui",zIndex:"6"});const title=document.createElement("div");title.textContent="Halle bearbeiten";style(title,{fontWeight:"700",marginBottom:"8px"});host.appendChild(title);const form=document.createElement("form"),grid=document.createElement("div");style(grid,{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(105px,120px)",gap:"8px 10px",alignItems:"center"});const length=makeNumberInput(hall.dimensions.length,{min:1}),width=makeNumberInput(hall.dimensions.width,{min:1}),eave=makeNumberInput(hall.dimensions.eaveHeight,{min:2}),roof=makeSelect(Object.entries(ROOF_LABELS).map(([value,label])=>({value,label})),hall.roof.type),peak=makeNumberInput(hall.roof.type==="flat"?"":hall.roof.peakHeight,{min:0}),spacing=makeNumberInput(hall.grid?.longitudinal?.spacing,{min:.5});for(const [l,c] of [["Länge [m]",length],["Breite [m]",width],["Traufhöhe [m]",eave],["Dachform",roof],["First / Hochpunkt [m]",peak],["Längsraster [m]",spacing]])addField(grid,l,c);form.appendChild(grid);
 const structural=document.createElement("div");structural.dataset.bpHallStructuralControls="bp-002";style(structural,{marginTop:"12px",paddingTop:"10px",borderTop:"1px solid rgba(255,255,255,.12)"});const sg=document.createElement("div");style(sg,{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(105px,120px)",gap:"8px 10px",alignItems:"center"});const colProfile=makeSelect(profileOptions(),hall.structure?.defaultColumnProfileRef),beamProfile=makeSelect(profileOptions(),hall.structure?.defaultPrimaryMemberProfileRef);colProfile.dataset.bpStructuralProfile="column";beamProfile.dataset.bpStructuralProfile="primary";addField(sg,"Stützenprofil",colProfile);addField(sg,"Hauptträgerprofil",beamProfile);structural.appendChild(sg);form.appendChild(structural);
 const wallControls=new Map();for(const id of HALL_EDIT_WALL_IDS){const w=hall.envelope?.walls?.[id]||{construction:"present",visible:true},row=document.createElement("div");style(row,{display:"grid",gridTemplateColumns:"1fr 100px 62px",gap:"6px",marginTop:"7px"});row.appendChild(makeLabel(WALL_LABELS[id]||id));const construction=makeSelect([{value:"present",label:"vorhanden"},{value:"open",label:"offen"}],w.construction),label=document.createElement("label"),visible=document.createElement("input");visible.type="checkbox";visible.checked=w.construction==="present"&&w.visible!==false;label.appendChild(visible);label.appendChild(document.createTextNode(" sichtbar"));row.appendChild(construction);row.appendChild(label);form.appendChild(row);wallControls.set(id,{construction,visible});}
 const status=document.createElement("div");style(status,{minHeight:"16px",marginTop:"10px",fontSize:"11px"});form.appendChild(status);const submit=document.createElement("button");submit.type="submit";submit.textContent="Halle übernehmen";style(submit,{width:"100%",padding:"9px",border:0,borderRadius:"8px",fontWeight:"700"});form.appendChild(submit);form.addEventListener("submit",e=>{e.preventDefault();const walls={};for(const[id,c]of wallControls)walls[id]={construction:c.construction.value,visible:c.construction.value==="present"&&c.visible.checked};const type=roof.value,sr=commitHallStructuralEdit({store,bus,reason:"bp-002:rapid-hall-edit",changes:{dimensions:{length:Number(length.value),width:Number(width.value),eaveHeight:Number(eave.value)},roof:{type,peakHeight:type==="flat"?null:Number(peak.value)},grid:{longitudinal:{spacing:Number(spacing.value)}},envelope:{walls},columnProfileRef:colProfile.value,primaryMemberProfileRef:beamProfile.value}});status.textContent=sr.committed?(sr.warnings||[]).join(" · "):(sr.errors||[]).join(" · ");});host.appendChild(form);sceneCtx.container.appendChild(host);editorHost=host;}
 async function mount(){if(sceneCtx)return;const project=currentProject();if(!project?.hall){renderCreateForm();return;}sceneCtx=initScene({rootEl});sceneCtx.mount();rootEl.style.position="relative";rootEl.style.overflow="hidden";try{const built=await ModelFactory.build(project);if(!built?.group)throw new Error("Hall generator returned no group.");sceneCtx.scene.add(built.group);currentGroup=built.group;elementMeshes=built.elementMeshes||new Map();frameHall(built);renderEditor();rootEl.dataset.hall3dStatus="ready";rootEl.dataset.hallAuthority="app.project.hall";rootEl.dataset.hallElementCount=String(elementMeshes.size);}catch(error){try{sceneCtx.unmount();}catch(_){}sceneCtx=null;showStatus(`Halle kann nicht dargestellt werden: ${error?.message||"ungültige Hallendaten"}`,"invalid-hall");}}
 function unmount(){if(sceneCtx){try{if(currentGroup)sceneCtx.scene.remove(currentGroup);sceneCtx.unmount();}catch(_){}}sceneCtx=null;currentGroup=null;elementMeshes=new Map();editorHost=null;rootEl.innerHTML="";clearStatusAttributes();}
 bus.on("req:hall3d:rebuild",async()=>{const active=document.getElementById("active")?.textContent?.trim()||"",legacy=String(store.get("core")?.ui?.activeModule||"");if(active!=="projectPanel:hall3d"&&active!=="hall3d"&&legacy!=="hall3d")return;unmount();await mount();});return{mount,unmount};
}
